# Generated by Django 3.1.7 on 2021-05-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMart', '0002_keshav_saifee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saifee',
        ),
    ]
