# Generated by Django 3.1.7 on 2021-05-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMart', '0004_saifee_saras'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keshav',
            table='',
        ),
    ]
